# -*- coding: utf-8 -*-
"""Assignment 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DLSIHC2Z-W7JA9gcpW1MmUSGMjOEJqvJ
"""

#Enter the first name
print("Enter the first name")
first_name = input()
#Enter the middle name
print("Enter the middle name")
middle_name = input()
#Enter the last name
print("Enter the last name")
last_name = input()
fullnames = first_name + " " + middle_name + " " + last_name
#Enter the email
print("Enter the email address")
email = input()
#Enter the phone number
print("Enter the phone number")
phone = input()
#Enter the mailing address
print("Enter the mailing address")
mailing = input()
#Enter the city
print("Enter the City")
city = input()
#Enter the zip code
print("Enter the zip code")
zipcode = input()

#Enter the price of the House you wish to Buy
price = float(1000000.00)
print("Enter the house price")
price = input()
#Enter the credit score
print("Enter the credit score")
creditscore = input()
#Qualify for loans with the best interest rates
if creditscore >= 780 and creditscore <= 850:
    print("Excellent Credit")
    print("Zero Down Payment")
    downPayment = 0.0 * price
#Usually qualify for loans with the best interest rates
elif creditscore >= 740 and creditscore <= 779:
    print("Very Good")
    downPayment = 0.2 * price
#May face slightly higher loan Interest rates
elif creditscore >= 720 and 739:
    print("Above Average")
    downPayment = 0.3 * price
#May qualify for most loans of higher interest rates
elif creditscore >= 680 and 719:
    print("Average")
    downPayment = 0.6 * price
#May qualify for most loans at significant higher Interest rates
elif creditscore >= 620 and 679:
    print("Below Average")
    downPayment = 0.18 * price
#Usually has some credit issues; will probably not qualify for most loans
elif creditscore >= 580 and 619:
    print("Poor credit score")
    downPayment = 0.20 * price
#Facing extreme credit issue
else : creditscore < 520 
    print("Poor credit score")
     downPayment = 0.25 * price